version: '3.8'

services:
  pgbouncer:
    build:
      context: ./pgbouncer
      dockerfile: Dockerfile
    ports:
      - "6432:6432"

  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data
  
  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

volumes:
  postgres1_data:
  postgres2_data:
